language: node_js
node_js:
  - "8"

scripts:
  - npm test
  - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: https://reacts-gen.arcing.io
  on:
    branch: demo

ignore:
  - *.md

notifications:
  email: false