language: node_js
sudo: required
dist: trusty
node_js:
  - "8"

script:
  - npm run test:coverage
  - NODE_ENV=production npm run build
  - rm -rf !(dist|*.md|deployed*)
  - mv dist/index.html .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: demo

notifications:
  email: false