language: node_js
sudo: required
dist: trusty
node_js:
  - "8"

script:
  - npm test
  - npm run build
  - mv dist docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: demo

notifications:
  email: false