export enum TypeKeys {
    USER_GET = 'USER_GET',
    USER_SET = 'USER_SET',
    AUTH_LOGIN = 'AUTH_LOGIN',
    AUTH_ISLOGGEDIN = 'AUTH_ISLOGGEDIN',
    AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE',
    OTHER_ACTION = '__OTHER__ACTIONS',
}
